#!/bin/bash

cp -r nvim ~/.config
cp -r kitty ~/.config
cp -r i3  ~/.config
cp .ideavimrc ~/.ideavimrc
cp .tmux.conf ~/.tmux.conf

dconf load / < custom-shortcuts.conf 
dconf load / < custom-keybindings.conf

